class CreateInvoicePageLocators:
    list_create_new_invoice_xpath = "(//a[@class='nav-link'])[2]"
    link_create_new_invoice_xpath = "(//a[@routerlink='/create/new-invoice'])[1]"
    input_select_guest_xpath = "//*[@id='mat-input-1']"
    span_select_guest_name_xpath = "//span[contains( text( ), \"Anuththara Rathnayake - anurathnayake178@gmail.com\")]"
    input_reservation_number_xpath = "//input[@name='ConfirmationNumber']"
    input_room_name_xpath = "//input[@name='roomName']"
    option_room_name_xpath = "//span[contains(text(), 'One Bedroom Apartment')]"
    button_check_in_date_xpath = "(//button[@aria-label='Open calendar'])[1]"
    div_check_in_date_xpath = "(//div[normalize-space()='12'])[1]"
    button_check_out_date_xpath = "(//button[@aria-label='Open calendar'])[2]"
    div_check_out_date_xpath = "(//div[normalize-space()='21'])[1]"
    input_remark_xpath = "//input[@name='remarks']"
    hr_item_heading_xpath = "(//hr[@data-content='Itemized Details'])[1]"
    div_select_item_1_xpath = "//*[@id='mat-select-4']/div/div[1]/span"
    span_room_chargers_xpath = "//span[normalize-space()='Room Charges']"
    span_item_visa_charges_xpath = "//span[contains(text(), 'Room Charge')]"
    span_item_desert_safari_xpath = "//span[contains(text(), 'Visa Charges')]"
    icon_copy_item_xpath = "(//i[@title='Copy Item'][normalize-space()='library_add'])[1]"
    icon_delete_item_xpath = "(//i[@title='Delete Item'][normalize-space()='clear'])[3]"
    div_select_item_2_xpath = "//*[@id='mat-select-16']/div/div[2]/div"
    heading_discounts_xpath = "//h6[normalize-space()='Discounts']"
    span_select_offer_xpath = "//*[@id='mat-select-5']/div/div[1]/span"
    span_offer_xpath = "(//span[normalize-space()='Test Discount'])[1]"
    span_toggle_xpath = "(//span[@class='toggle'])[4]"
    button_save_xpath = "(//button[@class='btn btn-danger mat-raised-button'])[2]"
    button_add_new_item_xpath = "(//button[@class='btn btn-primary btn-sm text-capitalize'])[1]"
    button_add_new_terms_xpath = ("/html/body/app-root/app-layout/div/div[2]/app-create-invoice/"
                                  "div/div/div[1]/div/form/div[2]/div/div[7]/div[2]/div/div/button")

    icon_remove_item_xpath = "(//i[@title='Delete Item'][normalize-space()='clear'])[1]"
    heading_charges_xpath = "(//h6[normalize-space()='Charges'])[1]"
    icon_remove_charges_xpath = "(//i[@title='Delete Item'][normalize-space()='clear'])[1]"
    icon_remove_discount_xpath = "(//i[@title='Delete Item'])[1]"
    heading_general_terms_xpath = "(//h5[normalize-space()='General Terms'])[1]"
    heading_payment_terms_xpath = "(//h5[normalize-space()='Payment Terms'])[1]"
    icon_remove_general_terms_xpath = "(//i[@title='Delete Term'][normalize-space()='clear'])[1]"
    icon_remove_payment_terms_xpath = "(//i[@title='Delete Term'])[1]"
    icon_copy_charges_xpath = "(//i[@title='Copy Item'][normalize-space()='library_add'])[2]"
    icon_copy_discount_xpath = "(//i[@title='Copy Item'][normalize-space()='library_add'])[3]"
    span_add_new_discount_xpath = "//span[contains( text( ), \"Add New Discount\")]"
    span_general_term_xpath = "//*[@id='mat-select-6']/div/div[1]/span/span"
    span_payment_term_xpath = "//*[@id='mat-select-8']/div/div[1]/span/span"

