class InvoicePageLocators:
    list_invoices_xpath = "/html/body/app-root/app-layout/div/div[1]/app-sidebar-cmp/div[2]/ul/li[3]/a"
    img_actions_xpath = "//*[@id='invoiceTable']/tbody/tr[1]/td[9]/div/img"
    img_actions_paid_xpath = "(//img[@title='Actions'])[4]"
    div_view_xpath = "//*[@id='invoiceTable']/tbody/tr[1]/td[9]/div/ul/li[1]"
    div_view_paid_xpath = "//*[@id='invoiceTable']/tbody/tr[4]/td[9]/div/ul/li[1]/a"
    tr_page_end_xpath = "(//tr[@class='total-due ng-star-inserted'])[1]"
    button_close_xpath = "(//button[@type='button'])[3]"
    list_edit_xpath = "(//li)[77]"
    button_save_xpath = "(//button[@class='btn btn-danger mr-0 waves-effect'][normalize-space()='Save'])[1]"
    button_send_email_xpath = "(//button[@type='button'][normalize-space()='Send Email'])[1]"
    button_generate_link_xpath = "(//button[@type='button'][normalize-space()='Generate Link'])[1]"
    button_copy_link_xpath = "(//button[@id='notCopied'])[1]"
    hyperlink_close_xpath = "//*[@id='generateLinkpopup']/div/div/div[3]/div/a"
    button_print_and_preview_xpath = "(//button[@type='button'][normalize-space()='Preview and Print'])[1]"
    button_close_edit_xpath = "//*[@id='previewInvoice']/div/div/div[1]/button/span/i"
    input_search_xpath = "(//input[@id='listingSearch'])[1]"
    list_delete_xpath = "//*[@id='invoiceTable']/tbody/tr[1]/td[9]/div/ul/li[4]/a"
    button_accept_delete_xpath = "(//button[normalize-space()='Yes, delete it!'])[1]"
    hyperlink_receipt_xpath = "//*[@id='InvoicePopup']/div/div/div[2]/div/ul/li[2]/a"
    hyperlink_payments_logs_xpath = "(//a[normalize-space()='Payments Log'])[1]"
    hyperlink_mail_logs_xpath = "(//a[normalize-space()='Mails Log'])[1]"
    hyperlink_invoice_logs_xpath = "(//a[normalize-space()='Invoice Log'])[1]"
    button_cancel_xpath = "(//button[normalize-space()='Cancel'])[1]"
